### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'

### ISSUE THREAD

**Issue by JPatil22** [SJSUSpring21/Road-accident-prediction-USA#1]
Hi this is Alex,
I am encountering this error and thanks for ur help

python run.py
Traceback (most recent call last):
  File "E:\ROAD ACCIDENT prediction\trial2\Road-accident-prediction-USA-main\US_prediction\run.py", line 1, in <module>
    from app import create_app
  File "E:\ROAD ACCIDENT prediction\trial2\Road-accident-prediction-USA-main\US_prediction\app\__init__.py", line 4, in <module>
    from app.main.routes import main
  File "E:\ROAD ACCIDENT prediction\trial2\Road-accident-prediction-USA-main\US_prediction\app\main\routes.py", line 2, in <module>
    from app.api_call_pred import api_call
  File "E:\ROAD ACCIDENT prediction\trial2\Road-accident-prediction-USA-main\US_prediction\app\api_call_pred.py", line 22, in <module>
    model = joblib.load(script_path + "/app/model/model.pkl")
  File "E:\ROAD ACCIDENT prediction\trial2\Road-accident-prediction-USA-main\flask\lib\site-packages\joblib\numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "E:\ROAD ACCIDENT prediction\trial2\Road-accident-prediction-USA-main\flask\lib\site-packages\joblib\numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "C:\Users\alexr\AppData\Local\Programs\Python\Python39\lib\pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "C:\Users\alexr\AppData\Local\Programs\Python\Python39\lib\pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "C:\Users\alexr\AppData\Local\Programs\Python\Python39\lib\pickle.py", line 1579, in find_class
    __import__(module, level=0)
ModuleNotFoundError: **No module named 'sklearn.ensemble.forest'**
(flask)

**Comment by Marveloder** [comment]
well and good
